// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8uu51w736YMgLM-PR4jJR0Y1gdvcwORo',
    appId: '1:99785329225:web:fbcea9b797ef0ac2e5cd98',
    messagingSenderId: '99785329225',
    projectId: 'flutter-chat-3c558',
    authDomain: 'flutter-chat-3c558.firebaseapp.com',
    storageBucket: 'flutter-chat-3c558.appspot.com',
    measurementId: 'G-NNLVFRG38Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu2lpvmgI7RUmF7Fnj3afynv4vETvBT8Y',
    appId: '1:99785329225:android:a1807aca641f288fe5cd98',
    messagingSenderId: '99785329225',
    projectId: 'flutter-chat-3c558',
    storageBucket: 'flutter-chat-3c558.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzWx8jomdLStusGBfaXES8s-dGAZI4NKY',
    appId: '1:99785329225:ios:48604d7e3aa182d0e5cd98',
    messagingSenderId: '99785329225',
    projectId: 'flutter-chat-3c558',
    storageBucket: 'flutter-chat-3c558.appspot.com',
    iosBundleId: 'com.example.chatUsingFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzWx8jomdLStusGBfaXES8s-dGAZI4NKY',
    appId: '1:99785329225:ios:48604d7e3aa182d0e5cd98',
    messagingSenderId: '99785329225',
    projectId: 'flutter-chat-3c558',
    storageBucket: 'flutter-chat-3c558.appspot.com',
    iosBundleId: 'com.example.chatUsingFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8uu51w736YMgLM-PR4jJR0Y1gdvcwORo',
    appId: '1:99785329225:web:0c966f452d592ff2e5cd98',
    messagingSenderId: '99785329225',
    projectId: 'flutter-chat-3c558',
    authDomain: 'flutter-chat-3c558.firebaseapp.com',
    storageBucket: 'flutter-chat-3c558.appspot.com',
    measurementId: 'G-D9WJPTFDJX',
  );
}
